In [7]:
import pandas as pd
#Series (1D Data Structure)
s = pd.Series([10, 20, 30, 40])
print(s)
type(s)

0    10
1    20
2    30
3    40
dtype: int64

pandas.core.series.Series

In [12]:
#Example with Index
import pandas as pd
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s1)

a    10
b    20
c    30
dtype: int64

In [11]:
s1['a']

np.int64(10)

In [13]:
type(s1)

pandas.core.series.Series

In [14]:
#. DataFrame (2D Data Structure)
data = {
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 22]
}

df = pd.DataFrame(data)
print(df)

  Name  Age
0    A   20
1    B   21
2    C   22

In [15]:
df["Name"]      # column
df.iloc[0]      # row

Name     A
Age     20
Name: 0, dtype: object

In [16]:
pd.DataFrame(data) #same as df = pd.DataFrame(data)
#print(df)

  Name  Age
0    A   20
1    B   21
2    C   22

In [17]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [18]:
df.columns

Index(['Name', 'Age'], dtype='object')

creating dataFrames in pandas

In [21]:
import pandas as pd

data = {
    "Name": ["A", "B", "C"],
    "Age": [20, 25, 30]
}

df = pd.DataFrame(data)
print(df)
#Industry use: APIs, JSON → converted to DataFrame

  Name  Age
0    A   20
1    B   25
2    C   30

In [23]:
#From List of Lists
data = [
    ["A", 20],
    ["B", 25],
    ["C", 30]
]

df = pd.DataFrame(data, columns=["Name", "Age"])
df

  Name  Age
0    A   20
1    B   25
2    C   30

In [27]:
#From Dictionary of Lists

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}
 
df = pd.DataFrame(data)
df
#Each key becomes a column, and each list is the column data.

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [29]:
#From NumPy Arrays
import numpy as np
 
arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"])
df

#Make sure to provide column names!

   A  B
0  1  2
1  3  4

In [33]:
#From CSV Files
df = pd.read_csv("data.csv")
df

#Use options like: sep, header, names, index_col, usecols, nrows, etc.

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [46]:
df = pd.read_csv("data.csv", usecols=["Name", "school","marks"])
df

ValueError: Usecols do not match columns, columns expected but not found: ['Name']

In [42]:
df = pd.read_excel("data.xlsx")
df

FileNotFoundError: [Errno 2] No such file or directory: 'data.xlsx'

In [40]:
df = pd.read_csv("data.csv")

In [41]:
df

     name school  marks
0     raj    rrj     78
1   pooja    PPJ     45
2   swati    JJK     89
3  himani    KKL     56
4  aniket    IIO     89
5   sumit     NN     23
6   tejas     DD     52

In [49]:
import pandas as pd
df = pd.read_xlsx("data.xlsx")
df

AttributeError: module 'pandas' has no attribute 'read_xlsx'

In [48]:
pd.read_csv("data.csv", usecols=["name", "school","marks"])

     name school  marks
0     raj    rrj     78
1   pooja    PPJ     45
2   swati    JJK     89
3  himani    KKL     56
4  aniket    IIO     89
5   sumit     NN     23
6   tejas     DD     52

In [59]:
df = pd.read_json("data.json")
df

FileNotFoundError: File data.json does not exist

In [58]:
df = pd.read_csv(" https://gist.github.com/curran/a08a1080b88344b0c8a7")
df

ParserError: Error tokenizing data. C error: Expected 1 fields in line 37, saw 2

In [2]:
#Selection (Accessing Data)
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Age": [20, 25, 30],
    "Marks": [80, 90, 85]
})
df["Name"]
df[["Name", "Marks"]]

  Name  Marks
0    A     80
1    B     90
2    C     85

In [3]:
#Selecting Rows
#✔️ Using .iloc (index-based)
df.iloc[0]        # first row
df.iloc[0:2]      # slice rows

#✔️ Using .loc (label-based)
df.loc[0]

Name      A
Age      20
Marks    80
Name: 0, dtype: object